services:
  fastapi:
    environment:
      DATABASE_URL: postgresql://user:password@db/edmachina_challenge
    build: ./fastapi
    ports:
     - "8000:8000"
    depends_on:
     - db
    restart: 'always'
    networks:
      - default
    
  react:
    environment:
      REACT_APP_API_URL: http://localhost:8000
    restart: 'always'
    build: ./react
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - default

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edmachina_challenge
    ports:
      - "5432:5432"
    restart: 'always'